name: Copy files to CSGO Server
on:
    push:
      branches:
        - main
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: copy files via ssh key
      uses:  appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.CSGO_HOST }}
        username: ${{ secrets.CSGO_USERNAME }}
        key: ${{ secrets.CSGO_KEY }}
        source: "cfg/*.cfg"
        target: "test"
        overwrite: true
        debug: true
