name: Copy files to CSGO Server
on:
  # manual trigger on https://github.com/PlanetKiF/csgo/actions?query=workflow:%22Copy+files+to+CSGO+Server%22
  workflow_dispatch:
  # every push triggers this workflow
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: copy files via ssh key
      uses:  appleboy/scp-action@v0.1.1
      # https://github.com/marketplace/actions/scp-command-to-transfer-files
      with:
        host: ${{ secrets.CSGO_HOST }}
        username: ${{ secrets.CSGO_USERNAME }}
        key: ${{ secrets.CSGO_KEY }}
        source: "csgo/*"
        target: "test"
        overwrite: true
        debug: true
